### ISSUE TITLE
[Issue tracker] Checklist: Ideas for improvements

### ISSUE THREAD

**Issue by Wikinaut** [ether/ep_email_notifications#29]
This is an issue tracker and a checklist for collecting ideas for improvements. Everyone who can is invited to update this first post (for example, adding issue numbers or other references).

In the following, the abbreviation "enotif" stands for "Etherpad E-Mail Notification".

- [ ] add the name of the editor (or editors, if more than one during the *grace period*) to enotifs
- [ ] suppress enotifs of one's own changes
- [ ] add a direct link to the difference view between the current version and the last-seen-version of each recipient *) #30
- [ ] better handle *"grace periods"* to decrease numbers of superfluous enotifs, enotifs which came too early or too often
- [ ] allow user-definable enotif parameters (grace period, minimum number of changes before...)
- [ ] v2 - Get the modified contents from the API HTML diff and append that to the Email and make the email from the server HTML not plain text
- [ ] v2 - Keep a record of when a user was last on a pad

*) like programmed in`MediaWiki` enotifs: each recipient receives a customized mail with a customized link to the difference between "his/her" last seen version of that pad and the present version (time of clicking and visiting the pad, not the time, when the enotif was sent.)

**Comment by Wikinaut** [comment]
@brettcs I just want to point you to this "accumulative thread" of possible improvements, perhaps we can work togther on some of the points?

**Comment by brettcs** [comment]
Thanks for the heads up. I'll admit up front I'm unlikely to have much time for this. We have the plug-in installed at my work, and basically I'm given a little time to work on user-facing issues. Bigger code changes like this are less likely, especially since I'm not really fluent in JavaScript. But I'll keep this bug in mind if people ask about some of these issues. The grace period sounds especially nice.

**Comment by JohnMcLear** [comment]
Closing for now as issues should be the tracker, not a specific issue.
